version: "3.8"
services:
  backend:

    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - mcp_trendmicro
      - mcp_exabeam
      - mcp_elastic
      - mcp_jira
      - qdrant

  mcp_trendmicro:
    build: ./mcp_trendmicro
    env_file:
      - .env
    ports:
      - "9001:8001"

  mcp_exabeam:
    build: ./mcp_exabeam
    env_file:
      - .env
    ports:
      - "9002:8001"

  mcp_elastic:
    build: ./mcp_elastic
    env_file:
      - .env
    ports:
      - "9003:8001"

  mcp_jira:
    build: ./mcp_jira
    env_file:
      - .env
    ports:
      - "9004:8000"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6334:6333"
